### ISSUE TITLE
exporting PNG with alpha

### ISSUE THREAD

**Issue by Kubanis** [Hirourk/HASPaintLayers#4]
Hello, I just want to ask about exporting/baking texture with proper alpha (PNG)
The picture is describing the issue. Please am I doing something wrong?
How to achieve this?

![exporting](https://github.com/user-attachments/assets/2f87ea55-185f-40f3-87eb-35e84669818e)

**Comment by Hirourk** [comment]
Thank you for report :D
It is now fixed in latest release

**Comment by Kubanis** [comment]
> Thank you for report :D It is now fixed in latest release

Thank you so much, I've tried new version, but for some reason problem remains... can you please take  alook on th picture, if I am doing anything wrong?

![problem](https://github.com/user-attachments/assets/657d66ce-79c5-4a65-aa67-339a0dfa928d)

**Comment by Hirourk** [comment]
Can you share your blender file?

**Comment by Kubanis** [comment]
> Can you share your blender file?

Of couser - I would be super happy if you take a look on it!
There is teh scene - you will find 4 cubes named accordingly by teh technique used.
[texture_test_has.zip](https://github.com/user-attachments/files/18202471/texture_test_has.zip)
![Screenshot 2024-12-19 204412](https://github.com/user-attachments/assets/e7a29052-4fe7-4a8c-ab38-e9a4c42487f3)

**Comment by Hirourk** [comment]
![image](https://github.com/user-attachments/assets/9f26bfd5-91e5-4436-8b5f-258af21e1b4a)
Here I tested, and top right corner is exported and imported to blender. Let's try that, I re-uploaded the addon just in case.
Remove add-on from blender, reload blender scene, install from latest release, and test exporting

**Comment by Hirourk** [comment]
[HASPaintLayers_0841.zip](https://github.com/user-attachments/files/18203048/HASPaintLayers_0841.zip)
This version is 0.8.41 is the one I'm working now, and testing

**Comment by Kubanis** [comment]
> [HASPaintLayers_0841.zip](https://github.com/user-attachments/files/18203048/HASPaintLayers_0841.zip) This version is 0.8.41 is the one I'm working now, and testing

In this one export work perfectly - tahnk you so much. I really appreciate your fast help and I will recommend this amazing addon to everybody who I meet for sure! :)
